site_name: Guide des Stéréotypes
site_author: Caroline Clavel & Florian Dufour
site_decription: Un guide pour explorer, détourner et utiliser les stéréotypes dans tous vos univers narratifs.

copyright: Copyright &copy; 2025 Caroline Clavel & Florian Dufour

theme:
  name: material
  palette:
   primary: teal
   accent: amber

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  # - pymdownx.blocks.caption
